#!/bin/bash
INSTALL=/home/dfa/sobreira/alsina/sw
INPUT_PATH=/home/dfa/sobreira/alsina/DESWL/psf
OUTPUT_PATH=/home2/dfa/sobreira/alsina/ourcatalogs
TAG=y3a1-v10

END=64
for ((i=1;i<=END;i++)); do
    python /home/dfa/sobreira/alsina/DESWL/psf/run_piff_andres_MOF_test.py --file=$INPUT_PATH/run/zone029_$i.riz --tag=$TAG --work=$OUTPUT_PATH/$TAG --pixmappy=$INPUT_PATH/zone029.astro.orig --bands=grizY  --sex_dir=$INSTALL/sextractor/2195/install/bin --sex_config=$INPUT_PATH/y3.sex --sex_params=$INPUT_PATH/sex.param_piff --sex_filter=$INPUT_PATH/sex.conv --sex_nnw=$INPUT_PATH/sex.nnw --findstars_dir=$INSTALL/deswl_shapelets/install/bin --findstars_config=$INPUT_PATH/y3.config --tapebump_file=$INPUT_PATH/mask_ccdnum.txt --mag_cut=1 --max_mag=21 --reserve=0.2 --use_ngmix --run_piff=1 --piff_exe=$INSTALL/pyhton/2714/install/bin/piffify --piff_config=$INPUT_PATH/piff_andres.yaml --plot_fs --rm_files=0 --coad_catalog=$INPUT_PATH/COADD_MOF.fits --star_flag='star_flag'&
done


