#!/bin/bash
INSTALL=/home/dfa/sobreira/alsina/sw
INPUT_PATH=/home/dfa/sobreira/alsina/DESWL/psf
OUTPUT_PATH=/home2/dfa/sobreira/alsina/ourcatalogs
TAG=y3a1-v23

source /home/sw/masternode/intel/2015/install/composerxe/bin/compilervars.sh intel64
source /home/sw/masternode/intel/2015/install/mpi/impi/5.1.2.150/bin64/mpivars.sh

export PATH=/home/dfa/sobreira/alsina/sw/pyhton/2714/install/bin:$PATH
export PYTHONPATH=$PYTHONPATH:/home/dfa/sobreira/alsina/sw/galsim/install/lib/python2.7/site-packages
export PATH=/home/dfa/sobreira/alsina/sw/cfitsio/install/bin:$PATH
export LD_LIBRARY_PATH=/home/dfa/sobreira/alsina/sw/cfitsio/install/lib:/home/dfa/sobreira/alsina/sw/ccfits/25/install/lib:/home/dfa/sobreira/alsina/sw/tmv/install/lib:/home/dfa/sobreira/alsina/sw/boost/166/install/lib:$LD_LIBRARY_PATH

echo $VNODENUM
cd /home/dfa/sobreira/alsina/DESWL/psf/run

$INSTALL/pyhton/2714/install/bin/python $INPUT_PATH/run_rho2.py --file=$INPUT_PATH/astro/riz/zone_$VNODENUM.riz --tag=$TAG --work=$INPUT_PATH/$TAG
$INSTALL/pyhton/2714/install/bin/python $INPUT_PATH/plot_rho_outand.py --file=$INPUT_PATH/astro/riz/zone_$VNODENUM.riz --tag=rho2 --tag=$TAG --work=$INPUT_PATH/$TAG --outpath=$OUTPUT_PATH/$ZONE/rho
wait

for(( n=64 ; n< 64*2 ; n++ ))
$INSTALL/pyhton/2714/install/bin/python $INPUT_PATH/run_rho2.py --file=$INPUT_PATH/astro/riz/zone_$n.riz --tag=$TAG --work=$INPUT_PATH/$TAG
$INSTALL/pyhton/2714/install/bin/python $INPUT_PATH/plot_rho_outand.py --file=$INPUT_PATH/astro/riz/zone_$VNODENUM.riz --tag=rho2 --tag=$TAG --work=$INPUT_PATH/$TAG --outpath=$OUTPUT_PATH/$ZONE/rho
wait

for(( n=64*2 ; n< 64*3 ; n++ ))
$INSTALL/pyhton/2714/install/bin/python $INPUT_PATH/run_rho2.py --file=$INPUT_PATH/astro/riz/zone_$n.riz --tag=$TAG --work=$INPUT_PATH/$TAG
$INSTALL/pyhton/2714/install/bin/python $INPUT_PATH/plot_rho_outand.py --file=$INPUT_PATH/astro/riz/zone_$VNODENUM.riz --tag=rho2 --tag=$TAG --work=$INPUT_PATH/$TAG --outpath=$OUTPUT_PATH/$ZONE/rho
wait

for(( n=64*3 ; n< 64*4 ; n++ ))
$INSTALL/pyhton/2714/install/bin/python $INPUT_PATH/run_rho2.py --file=$INPUT_PATH/astro/riz/zone_$n.riz --tag=$TAG --work=$INPUT_PATH/$TAG
$INSTALL/pyhton/2714/install/bin/python $INPUT_PATH/plot_rho_outand.py --file=$INPUT_PATH/astro/riz/zone_$VNODENUM.riz --tag=rho2 --tag=$TAG --work=$INPUT_PATH/$TAG --outpath=$OUTPUT_PATH/$ZONE/rho


